---
# role: httpd
# file: handlers/main.yml

- name: Reload httpd service
  ansible.builtin.service:
    name: "{{ __httpd_service_name }}"
    state: reloaded
  when: not ansible_check_mode
  listen: httpd_reload
