---
# role: httpd
# file: molecule/dev/molecule.yml

dependency:
  name: "galaxy"
driver:
  name: "podman"
provisioner:
  name: "ansible"
  config_options:
    defaults:
      forks: 8
      interpreter_python: "auto_silent"
      allow_world_readable_tmpfiles: true
      callbacks_enabled: "ansible.posix.profile_tasks,ansible.posix.timer"
      callback_result_format: "yaml"
      remote_tmp: "/tmp/.ansible/tmp"
    ssh_connection:
      pipelining: true
  log: true
  playbooks:
    converge: "../resources/playbooks/converge.yml"
    verify: "../resources/playbooks/verify.yml"
    side_effect: "../resources/playbooks/side_effect.yml"
  inventory:
    group_vars:
      all:
        __httpd_test_module_paths:
          Debian: "/usr/lib/apache2/modules/mod_headers.so"
          RedHat: "/etc/httpd/modules/mod_headers.so"
          Suse: "/usr/lib64/apache2-{{ httpd_mpm }}/mod_headers.so"
        httpd_extra_modules:
          - name: "headers_module"
            path: "{{ __httpd_test_module_paths[ansible_facts.os_family] }}"
          - name: "proxy_module"
            file: "mod_proxy.so"
          - name: "proxy_http_module"
            file: "mod_proxy_http.so"
        httpd_listen:
          - port: 8080
          - port: 8443
            protocol: "https"
        httpd_vhost_files:
          - name: "100-molecule-redirect.conf"
            content: |-
              <VirtualHost *:8080>
                  ServerName molecule.example
                  Header always set X-Molecule-Module "path-only"
                  Redirect permanent / https://molecule.example/
              </VirtualHost>
          - name: "200-molecule-proxy.conf"
            content: |-
              <VirtualHost *:8080>
                  ServerName proxy.molecule.example
                  ProxyPass / http://127.0.0.1:8081/
              </VirtualHost>
verifier:
  name: "ansible"
scenario:
  name: "dev"
platforms:
  - name: "almalinux-latest-httpd"
    image: "docker.io/jomrr/molecule-almalinux:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "debian-latest-httpd"
    image: "docker.io/jomrr/molecule-debian:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "fedora-latest-httpd"
    image: "docker.io/jomrr/molecule-fedora:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "opensuse-leap-latest-httpd"
    image: "docker.io/jomrr/molecule-opensuse-leap:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "opensuse-tumbleweed-latest-httpd"
    image: "docker.io/jomrr/molecule-opensuse-tumbleweed:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "ubuntu-latest-httpd"
    image: "docker.io/jomrr/molecule-ubuntu:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
