---
# role: httpd
# file: molecule/dev/molecule.yml

dependency:
  name: "galaxy"
driver:
  name: "podman"
provisioner:
  name: "ansible"
  config_options:
    defaults:
      forks: 8
      interpreter_python: "auto_silent"
      allow_world_readable_tmpfiles: true
      callbacks_enabled: "ansible.posix.profile_tasks,ansible.posix.timer"
      callback_result_format: "yaml"
      remote_tmp: "/tmp/.ansible/tmp"
    ssh_connection:
      pipelining: true
  log: true
  playbooks:
    converge: "../resources/playbooks/converge.yml"
    verify: "../resources/playbooks/verify.yml"
  inventory:
    group_vars:
      all:
        httpd_listen:
          - port: 8080
          - port: 8443
            protocol: "https"
        httpd_vhost_files:
          - name: "100-molecule-redirect.conf"
            content: |-
              <VirtualHost *:8080>
                  ServerName molecule.example
                  Redirect permanent / https://molecule.example/
              </VirtualHost>
verifier:
  name: "ansible"
scenario:
  name: "dev"
platforms:
  - name: almalinux-latest-httpd
    image: "docker.io/jomrr/molecule-almalinux:latest"
    pre_build_image: true
    override_command: false
    systemd: true
  - name: debian-latest-httpd
    image: "docker.io/jomrr/molecule-debian:latest"
    pre_build_image: true
    override_command: false
    systemd: true
  - name: fedora-latest-httpd
    image: "docker.io/jomrr/molecule-fedora:latest"
    pre_build_image: true
    override_command: false
    systemd: true
  - name: opensuse-leap-latest-httpd
    image: "docker.io/jomrr/molecule-opensuse-leap:latest"
    pre_build_image: true
    override_command: false
    systemd: true
  - name: opensuse-tumbleweed-latest-httpd
    image: "docker.io/jomrr/molecule-opensuse-tumbleweed:latest"
    pre_build_image: true
    override_command: false
    systemd: true
  - name: ubuntu-latest-httpd
    image: "docker.io/jomrr/molecule-ubuntu:latest"
    pre_build_image: true
    override_command: false
    systemd: true
