# role: jomrr.httpd
# file: molecule/resources/playbooks/prepare.yml

- name: "PLAYBOOK | Prepare | httpd"
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: "HTTPD | Update apk cache"
      community.general.apk:
        update_cache: true
      when: ansible_pkg_mgr == "apk"

    - name: "HTTPD | Update apt cache"
      ansible.builtin.apt:
        update_cache: true
      when: ansible_pkg_mgr == "apt"

    - name: "HTTPD | Update dnf cache"
      ansible.builtin.dnf:
        update_cache: true
      when: ansible_pkg_mgr == "dnf"

    - name: "HTTPD | Update pacman cache"
      community.general.pacman:
        update_cache: true
      when: ansible_pkg_mgr == "pacman"

    - name: "HTTPD | Update zypper cache"
      community.general.zypper:
        name: sudo
        update_cache: true
      when: ansible_pkg_mgr == "zypper"
